version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:80"
    env_file:
      - ./backend/.env.example

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env.example
