version: '3'

services:
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:80"
    env_file:
      - .env.example

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  db:
    image: postgres:16
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env.example
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    env_file:
      - .env.example
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password

volumes:
  postgres_db:

networks:
  default:
